[package]
name = "jab"
version = "0.1.0"
edition = "2024"

[dependencies]

whoami = "=0.9.0"
serde = { version = "1.0", features = ["derive"] }
pty = "0.2.2"
serde_derive = "1.0.136"
serde_json = "1.0.79"
tokio = "1.45.1"
once_cell = "1.21.3"
